apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: collector
  name: collector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: collector
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yaml
          image: otel/opentelemetry-collector-contrib:0.78.0
          name: collector
          ports:
            - containerPort: 4317
            - containerPort: 3030
            - containerPort: 8889
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-contrib.yaml
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: opentelemetry-config
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-config
  namespace: default
  labels:
    io.kompose.service: collector
data:
  otel-collector-contrib.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:3030"
    exporters:
      logging:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging,prometheus]
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: collector
  namespace: default
spec:
  ports:
    - name: "4317"
      protocol: TCP
      port: 4317
      targetPort: 4317
  selector:
    io.kompose.service: collector
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: collector-3030
  namespace: default
spec:
  ports:
    - name: "3030"
      protocol: TCP
      port: 3030
      targetPort: 3030
  selector:
    io.kompose.service: collector
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: collector-8889
  namespace: default
spec:
  ports:
    - name: "8889"
      protocol: TCP
      port: 8889
      targetPort: 8889
  selector:
    io.kompose.service: collector
