apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: demo
  labels:
    io.kompose.service: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana:9.4.3
      volumeMounts:
        - name: config-volume
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          subPath: grafana-datasources.yaml
      env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: 123456
        # - name: GF_AUTH_ANONYMOUS_ENABLED
        #   value: "true"
        # - name: GF_AUTH_ANONYMOUS_ORG_ROLE
        #   value: "Admin"
        # - name: GF_AUTH_DISABLE_LOGIN_FORM
        #   value: "true"
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "traceqlEditor"
        - name: GF_SERVER_HTTP_PORT
          value: "3002"
      ports:
        - containerPort: 3002
      resources: {}
  volumes:
    - name: config-volume
      configMap:
        name: grafana-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: demo
  labels:
    io.kompose.service: grafana
data:
  grafana-datasources.yaml: |
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      orgId: 1
      url: http://prometheus:9090
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
      jsonData:
        httpMethod: GET

    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      basicAuth: false
      isDefault: false
      version: 1
      editable: true
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: grafana
  namespace: demo
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: grafana