apiVersion: v1
kind: Pod
metadata:
  name: loki
  namespace: demo
  labels:
    io.kompose.service: loki
spec:
  containers:
    - name: loki
      image: grafana/loki:2.8.2
      args:
        - -config.file=/etc/loki/local-config.yaml
        - -log.level=error
      ports:
        - containerPort: 3100
        - containerPort: 9096
      resources: {}
      volumeMounts:
        - name: config-volume
          mountPath: /etc/loki/local-config.yaml
          subPath: loki-local-config.yaml
  volumes:
    - name: config-volume
      configMap:
        name: loki-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: demo
  labels:
    io.kompose.service: loki
data:
  loki-local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://localhost:9093

    analytics:
      reporting_enabled: false
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: loki
  namespace: demo
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
  selector:
    io.kompose.service: loki
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: loki-9096
  namespace: demo
spec:
  ports:
    - name: "9096"
      port: 9096
      targetPort: 9096
  selector:
    io.kompose.service: loki