apiVersion: v1
kind: Pod
metadata:
  name: collector
  namespace: demo
  labels:
    io.kompose.service: collector
spec:
  containers:
    - name: collector
      image: otel/opentelemetry-collector-contrib:0.78.0
      args:
        - --config=/etc/otel-collector-config.yaml
      volumeMounts:
        - name: config-volume
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-contrib.yaml
      ports:
        - containerPort: 4317
        - containerPort: 3030
        - containerPort: 8889
      resources: {}
  volumes:
    - name: config-volume
      configMap:
        name: opentelemetry-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-config
  namespace: demo
  labels:
    io.kompose.service: collector
data:
  otel-collector-contrib.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:3030"
    exporters:
      logging:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging,prometheus]
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: collector
  namespace: demo
spec:
  ports:
    - name: "4317"
      port: 4317
      targetPort: 4317
  selector:
    io.kompose.service: collector
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: collector-3030
  namespace: demo
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
  selector:
    io.kompose.service: collector
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  name: collector-8889
  namespace: demo
spec:
  ports:
    - name: "8889"
      port: 8889
      targetPort: 8889
  selector:
    io.kompose.service: collector
